export namespace Flag {
  export const ANYAGENT_AUTO_SHARE = truthy("ANYAGENT_AUTO_SHARE")
  export const ANYAGENT_CONFIG = process.env["ANYAGENT_CONFIG"]
  export const ANYAGENT_CONFIG_DIR = process.env["ANYAGENT_CONFIG_DIR"]
  export const ANYAGENT_CONFIG_CONTENT = process.env["ANYAGENT_CONFIG_CONTENT"]
  export const ANYAGENT_DISABLE_AUTOUPDATE = truthy("ANYAGENT_DISABLE_AUTOUPDATE")
  export const ANYAGENT_DISABLE_PRUNE = truthy("ANYAGENT_DISABLE_PRUNE")
  export const ANYAGENT_PERMISSION = process.env["ANYAGENT_PERMISSION"]
  export const ANYAGENT_DISABLE_DEFAULT_PLUGINS = truthy("ANYAGENT_DISABLE_DEFAULT_PLUGINS")
  export const ANYAGENT_DISABLE_LSP_DOWNLOAD = truthy("ANYAGENT_DISABLE_LSP_DOWNLOAD")
  export const ANYAGENT_ENABLE_EXPERIMENTAL_MODELS = truthy("ANYAGENT_ENABLE_EXPERIMENTAL_MODELS")
  export const ANYAGENT_DISABLE_AUTOCOMPACT = truthy("ANYAGENT_DISABLE_AUTOCOMPACT")
  export const ANYAGENT_FAKE_VCS = process.env["ANYAGENT_FAKE_VCS"]

  // Experimental
  export const ANYAGENT_EXPERIMENTAL = truthy("ANYAGENT_EXPERIMENTAL")
  export const ANYAGENT_EXPERIMENTAL_WATCHER = truthy("ANYAGENT_EXPERIMENTAL_WATCHER")
  export const ANYAGENT_EXPERIMENTAL_TURN_SUMMARY = truthy("ANYAGENT_EXPERIMENTAL_TURN_SUMMARY")
  export const ANYAGENT_EXPERIMENTAL_NO_BOOTSTRAP = truthy("ANYAGENT_EXPERIMENTAL_NO_BOOTSTRAP")
  export const ANYAGENT_EXPERIMENTAL_EXA = ANYAGENT_EXPERIMENTAL || truthy("ANYAGENT_EXPERIMENTAL_EXA")

  function truthy(key: string) {
    const value = process.env[key]?.toLowerCase()
    return value === "true" || value === "1"
  }
}
